baseurl = "https://nsheremet.pw/"
languageCode = "en-US"
title = "Nazarii Sheremet"
# Enable comments by entering your Disqus shortname
disqusShortname = "nsheremet"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpeg"
  author = "Nazarii Sheremet"
  description = "I'm Software Developer. Working with Ruby/MRuby/Rust/Go/C/C++. Geek. Husband."

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "nsheremet"
  Email         = "nazarii.sheremet@gmail.com"
  LinkedIn      = "nsheremet"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/files/Nazarii_Sheremet_CV.pdf"
